import { createHmac } from "node:crypto";
import { isHexString } from "ethers";

/**
 * Deterministic per-voter, per-election nullifier.
 *
 *   message   = "VOTECHAIN-NULLIFIER-V1\0" || electionId (32 raw bytes) || u32be(len(uid)) || uid (UTF-8)
 *   nullifier = HMAC-SHA256(NULLIFIER_SECRET, message)         // all 32 bytes, never truncated
 *
 * The input is an INTERNAL random voter uid, never the public voterId. Every variable-length part
 * is length-prefixed and the election id is fixed width, so two different (election, uid) pairs can
 * never produce the same message. No normalisation or trimming is applied to the uid: it is an opaque
 * identifier generated by the backend (ill-formed UTF-16 is rejected, since UTF-8 cannot represent it injectively).
 */

export const NULLIFIER_DOMAIN = Buffer.from("VOTECHAIN-NULLIFIER-V1\0", "utf8");
export const MIN_SECRET_BYTES = 32;
const MAX_UID_BYTES = 1024;

export function encodeNullifierMessage(electionId, voterUid) {
  if (typeof electionId !== "string" || !isHexString(electionId, 32)) throw new TypeError("electionId must be a bytes32 hex string");
  if (typeof voterUid !== "string" || voterUid.length === 0) throw new TypeError("voterUid must be a non-empty string");
  // UTF-8 encoding replaces a lone surrogate with U+FFFD, so two different strings would share one
  // byte sequence (and one nullifier). Refusing ill-formed text keeps the encoding injective.
  if (!voterUid.isWellFormed()) throw new TypeError("voterUid must be well-formed Unicode (no lone surrogates)");
  const uid = Buffer.from(voterUid, "utf8");
  if (uid.length > MAX_UID_BYTES) throw new RangeError(`voterUid is longer than ${MAX_UID_BYTES} bytes`);
  const length = Buffer.alloc(4);
  length.writeUInt32BE(uid.length, 0);
  return Buffer.concat([NULLIFIER_DOMAIN, Buffer.from(electionId.slice(2), "hex"), length, uid]);
}

/**
 * @param {{ secret: Buffer | Uint8Array, electionId: string, voterUid: string }} input
 * @returns {string} 0x-prefixed bytes32
 */
export function deriveNullifier({ secret, electionId, voterUid }) {
  if (!(secret instanceof Uint8Array) || secret.length < MIN_SECRET_BYTES) {
    throw new TypeError(`secret must be at least ${MIN_SECRET_BYTES} bytes`);
  }
  const digest = createHmac("sha256", secret).update(encodeNullifierMessage(electionId, voterUid)).digest();
  return "0x" + digest.toString("hex");
}
