// Copies the RELAYER-SIDE SUBSET of the VoteChainV3 ABI (and the Semaphore group reads and errors it needs) into src/chain/generated/.
//   node scripts/sync-abi.js          copy
//   node scripts/sync-abi.js --check  exit 1 if the committed copy differs from the compiled contracts
// The compiled artifacts of ../smart-contract-v3 (run `npm run compile` there first) are the single source of truth; never edit the copy by hand.
// The subset is deliberate: the relayer's ABI contains NO commitment-issuance function, so this service cannot even encode one.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const artifacts = path.resolve(root, "../smart-contract-v3/artifacts");
const VOTECHAIN = path.join(artifacts, "contracts/VoteChainV3.sol/VoteChainV3.json");
const SEMAPHORE = path.join(artifacts, "@semaphore-protocol/contracts/Semaphore.sol/Semaphore.json");
const target = path.join(root, "src/chain/generated/votechainv3.relay.abi.json");
const check = process.argv.includes("--check");

const SEMAPHORE_ERRORS = ["Semaphore__GroupDoesNotExist", "Semaphore__GroupHasNoMembers", "Semaphore__InvalidProof", "Semaphore__MerkleTreeDepthIsNotSupported", "Semaphore__MerkleTreeRootIsExpired", "Semaphore__MerkleTreeRootIsNotPartOfTheGroup", "Semaphore__YouAreUsingTheSameNullifierTwice"];
const WANTED = {
  contract: {
    function: ["ELECTION_ID", "SEMAPHORE_DEPTH", "ballotHashOf", "constituencyCount", "constituencyIdAt", "getConstituency", "issuer", "nullifierUsed", "owner", "phase", "semaphore", "submitBallot", "trusteeConfiguration"],
    event: ["BallotRecorded"],
    error: ["CoordinateOutOfField", "IdentityC1", "InvalidMembershipProof", "InvalidValidityProof", "NullifierAlreadyUsed", "NullifierOutOfField", "UnknownConstituency", "WrongCoordinateCount", "WrongPhase", "WrongSemaphoreDepth"],
  },
  semaphore: { function: ["getMerkleTreeRoot", "getMerkleTreeSize"], event: ["MembersAdded"], error: SEMAPHORE_ERRORS },
};

function pick(abi, wanted) {
  const out = [];
  for (const type of ["function", "event", "error"]) {
    for (const name of wanted[type]) {
      const fragment = abi.find((f) => f.type === type && f.name === name);
      if (!fragment) throw new Error(`the compiled ABI has no ${type} "${name}"`);
      out.push(fragment);
    }
  }
  return out;
}

for (const file of [VOTECHAIN, SEMAPHORE]) {
  if (!fs.existsSync(file)) {
    console.error(`Compiled artifact not found: ${path.relative(root, file)}\nRun "npm run compile" in smart-contract-v3/ first.`);
    process.exit(1);
  }
}
const read = (file) => JSON.parse(fs.readFileSync(file, "utf8")).abi;
const generated = {
  note: "GENERATED by scripts/sync-abi.js from ../smart-contract-v3 (relayer-side subset). Do not edit.",
  contractAbi: pick(read(VOTECHAIN), WANTED.contract),
  semaphoreAbi: pick(read(SEMAPHORE), WANTED.semaphore),
};
const wanted = JSON.stringify(generated, null, 2) + "\n";
const current = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : null;

if (check) {
  if (current === wanted) {
    console.log("relay ABI copy is in sync with the compiled contracts");
    process.exit(0);
  }
  console.error('relay ABI copy is OUT OF SYNC with the compiled contracts. Run "npm run sync:abi".');
  process.exit(1);
}
fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target, wanted);
console.log(current === wanted ? "ABI already up to date" : `ABI copied -> ${path.relative(root, target)}`);
